---
blank_issues_enabled: false
contact_links:
  - name: Access your data everywhere in your app with EnvironmentObject Community Support
    url: https://github.com/developer-academy-unina/Tutorial-Access-your-data-everywhere-in-your-app-with-EnvironmentObject/discussions
    about: Please ask and answer questions here.
